version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: activate virtual environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
      - run:
          name: install dependencies
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
