name: Python application

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pylint
        pip install -r requirements.txt
    - name: Test with pytest
      env:
        MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      run: |
        pytest
    - name: Lint with pylint
      run: |
        find . -name "*.py" -exec pylint --extension-pkg-whitelist='pydantic' {} +;
